"""Create the initial local schema.

Revision ID: 0001
Revises:
Create Date: 2026-08-05 02:08:51.560977
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.String(length=100), nullable=True),
        sa.Column("taxonomy_version", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "parent_id IS NULL OR parent_id != id", name="ck_categories_parent"
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "taxonomy_version", "name", name="uq_categories_version_name"
        ),
    )
    op.create_table(
        "financial_roles",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.bulk_insert(
        sa.table(
            "financial_roles",
            sa.column("id", sa.String()),
            sa.column("name", sa.String()),
        ),
        [
            {"id": "income", "name": "Income"},
            {"id": "expense", "name": "Expense"},
            {"id": "transfer_in", "name": "Transfer In"},
            {"id": "transfer_out", "name": "Transfer Out"},
            {"id": "refund", "name": "Refund"},
            {"id": "reimbursement", "name": "Reimbursement"},
            {"id": "cash_withdrawal", "name": "Cash Withdrawal"},
            {"id": "excluded", "name": "Excluded"},
            {"id": "unknown", "name": "Unknown"},
        ],
    )
    op.bulk_insert(
        sa.table(
            "categories",
            sa.column("id", sa.String()),
            sa.column("name", sa.String()),
            sa.column("parent_id", sa.String()),
            sa.column("taxonomy_version", sa.String()),
            sa.column("is_active", sa.Boolean()),
        ),
        [
            {
                "id": category_id,
                "name": name,
                "parent_id": None,
                "taxonomy_version": "1.0",
                "is_active": True,
            }
            for category_id, name in (
                ("income", "Income"),
                ("housing", "Housing"),
                ("utilities", "Utilities"),
                ("groceries", "Groceries"),
                ("eating_out", "Eating Out"),
                ("transport", "Transport"),
                ("shopping", "Shopping"),
                ("health", "Health"),
                ("education", "Education"),
                ("entertainment", "Entertainment"),
                ("travel", "Travel"),
                ("subscriptions", "Subscriptions"),
                ("fees_and_charges", "Fees and Charges"),
                ("transfers", "Transfers"),
                ("cash_withdrawal", "Cash Withdrawal"),
                ("savings", "Savings"),
                ("refund", "Refund"),
                ("other", "Other"),
                ("needs_review", "Needs Review"),
            )
        ],
    )
    op.create_table(
        "model_metadata",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("model_version", sa.String(length=100), nullable=False),
        sa.Column("task", sa.String(length=100), nullable=False),
        sa.Column("artifact_path", sa.String(length=500), nullable=True),
        sa.Column("training_cutoff", sa.Date(), nullable=True),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("parameters_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "model_name", "model_version", name="uq_model_metadata_version"
        ),
    )
    op.create_table(
        "user_profiles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=True),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("base_currency = 'GBP'", name="ck_user_profiles_currency"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_profile_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("institution_label", sa.String(length=100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "account_type IN ('current', 'checking', 'savings')",
            name="ck_accounts_type",
        ),
        sa.CheckConstraint("currency = 'GBP'", name="ck_accounts_currency"),
        sa.ForeignKeyConstraint(
            ["user_profile_id"], ["user_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_profile_id", "name", name="uq_accounts_user_name"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_accounts_user_profile_id"), ["user_profile_id"], unique=False
        )

    op.create_table(
        "budgets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_profile_id", sa.String(length=36), nullable=False),
        sa.Column("category_id", sa.String(length=100), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("amount_limit", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.CheckConstraint("currency = 'GBP'", name="ck_budgets_currency"),
        sa.CheckConstraint("amount_limit >= 0", name="ck_budgets_amount"),
        sa.CheckConstraint("period_end >= period_start", name="ck_budgets_dates"),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_profile_id"], ["user_profiles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_profile_id",
            "category_id",
            "period_start",
            "period_end",
            name="uq_budgets_period",
        ),
    )
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_budgets_user_profile_id"), ["user_profile_id"], unique=False
        )

    op.create_table(
        "import_batches",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.Column("imported_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "source_type IN ('csv', 'digital_pdf', 'ocr_pdf')",
            name="ck_import_batches_source_type",
        ),
        sa.CheckConstraint(
            "verification_status IN "
            "('unverified', 'needs_review', 'verified', 'rejected')",
            name="ck_import_batches_verification",
        ),
        sa.CheckConstraint("byte_size > 0", name="ck_import_batches_byte_size"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "file_hash", name="uq_import_batches_file"),
    )
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_import_batches_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "recurring_series",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("merchant_pattern", sa.String(length=500), nullable=False),
        sa.Column("expected_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("interval_days", sa.Integer(), nullable=False),
        sa.Column("financial_role_id", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("interval_days > 0", name="ck_recurring_series_interval"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["financial_role_id"], ["financial_roles.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recurring_series", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recurring_series_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "savings_goals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("target_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("current_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("current_amount >= 0", name="ck_savings_goals_current"),
        sa.CheckConstraint("target_amount > 0", name="ck_savings_goals_target"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "name", name="uq_savings_goals_account_name"),
    )
    with op.batch_alter_table("savings_goals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_savings_goals_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "scenarios",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("assumptions_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "name", name="uq_scenarios_account_name"),
    )
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_scenarios_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "balance_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("import_batch_id", sa.String(length=36), nullable=True),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("verification_status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "(source = 'manual' AND import_batch_id IS NULL) OR "
            "(source != 'manual' AND import_batch_id IS NOT NULL)",
            name="ck_balance_snapshots_lineage",
        ),
        sa.CheckConstraint("currency = 'GBP'", name="ck_balance_snapshots_currency"),
        sa.CheckConstraint(
            "source IN ('statement_closing', 'running_balance', 'manual')",
            name="ck_balance_snapshots_source",
        ),
        sa.CheckConstraint(
            "verification_status IN "
            "('unverified', 'needs_review', 'verified', 'rejected')",
            name="ck_balance_snapshots_verification",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["import_batch_id"], ["import_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("balance_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_balance_snapshots_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "forecast_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("scenario_id", sa.String(length=36), nullable=True),
        sa.Column("model_metadata_id", sa.String(length=36), nullable=True),
        sa.Column("forecast_start", sa.Date(), nullable=False),
        sa.Column("forecast_end", sa.Date(), nullable=False),
        sa.Column("output_json", sa.JSON(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "forecast_end >= forecast_start", name="ck_forecast_runs_dates"
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["model_metadata_id"], ["model_metadata.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("forecast_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forecast_runs_account_id"), ["account_id"], unique=False
        )

    op.create_table(
        "import_contexts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("import_batch_id", sa.String(length=36), nullable=False),
        sa.Column("flags_json", sa.JSON(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["import_batch_id"], ["import_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_batch_id"),
    )
    op.create_table(
        "raw_transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("import_batch_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=20), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("page_record_number", sa.Integer(), nullable=True),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("original_date_text", sa.Text(), nullable=False),
        sa.Column("original_description", sa.Text(), nullable=False),
        sa.Column("original_amount_text", sa.Text(), nullable=True),
        sa.Column("parser_name", sa.String(length=100), nullable=False),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("source_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("canonical_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("review_status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(source_type = 'csv' AND source_row_number IS NOT NULL "
            "AND page_number IS NULL AND page_record_number IS NULL) OR "
            "(source_type != 'csv' AND source_row_number IS NULL "
            "AND page_number IS NOT NULL AND page_record_number IS NOT NULL)",
            name="ck_raw_transactions_location",
        ),
        sa.CheckConstraint(
            "review_status IN ('pending', 'needs_review', 'confirmed', 'rejected')",
            name="ck_raw_transactions_review",
        ),
        sa.CheckConstraint(
            "source_type IN ('csv', 'digital_pdf', 'ocr_pdf')",
            name="ck_raw_transactions_source_type",
        ),
        sa.ForeignKeyConstraint(
            ["import_batch_id"], ["import_batches.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_fingerprint"),
    )
    with op.batch_alter_table("raw_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_raw_transactions_canonical_fingerprint"),
            ["canonical_fingerprint"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_raw_transactions_import_batch_id"),
            ["import_batch_id"],
            unique=False,
        )

    op.create_table(
        "statement_coverages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("import_context_id", sa.String(length=36), nullable=False),
        sa.Column("statement_start_date", sa.Date(), nullable=False),
        sa.Column("statement_end_date", sa.Date(), nullable=False),
        sa.Column("coverage_status", sa.String(length=20), nullable=False),
        sa.Column("missing_periods_json", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "coverage_status IN "
            "('complete', 'partial', 'gapped', 'overlapping', 'unknown')",
            name="ck_statement_coverages_status",
        ),
        sa.CheckConstraint(
            "statement_end_date >= statement_start_date",
            name="ck_statement_coverages_dates",
        ),
        sa.ForeignKeyConstraint(
            ["import_context_id"], ["import_contexts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("import_context_id"),
    )
    op.create_table(
        "verified_transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("raw_transaction_id", sa.String(length=36), nullable=False),
        sa.Column("account_id", sa.String(length=36), nullable=False),
        sa.Column("transaction_date", sa.Date(), nullable=False),
        sa.Column("posting_date", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("merchant", sa.String(length=500), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("transaction_type", sa.String(length=255), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("category_id", sa.String(length=100), nullable=True),
        sa.Column("financial_role_id", sa.String(length=50), nullable=False),
        sa.Column("verified_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(amount > 0 AND direction = 'inflow') OR "
            "(amount < 0 AND direction = 'outflow')",
            name="ck_verified_transactions_signed_direction",
        ),
        sa.CheckConstraint(
            "currency = 'GBP'", name="ck_verified_transactions_currency"
        ),
        sa.CheckConstraint(
            "direction IN ('inflow', 'outflow')",
            name="ck_verified_transactions_direction",
        ),
        sa.CheckConstraint("amount != 0", name="ck_verified_transactions_amount"),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["financial_role_id"], ["financial_roles.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["raw_transaction_id"], ["raw_transactions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id", "external_id", name="uq_verified_transactions_external_id"
        ),
        sa.UniqueConstraint("raw_transaction_id"),
    )
    with op.batch_alter_table("verified_transactions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_verified_transactions_account_date_amount",
            ["account_id", "transaction_date", "amount"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_verified_transactions_account_id"),
            ["account_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_verified_transactions_category_id"),
            ["category_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_verified_transactions_merchant"), ["merchant"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_verified_transactions_transaction_date"),
            ["transaction_date"],
            unique=False,
        )

    op.create_table(
        "anomaly_alerts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("verified_transaction_id", sa.String(length=36), nullable=False),
        sa.Column("model_metadata_id", sa.String(length=36), nullable=True),
        sa.Column("score", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('open', 'reviewed', 'dismissed')",
            name="ck_anomaly_alerts_status",
        ),
        sa.CheckConstraint("score >= 0 AND score <= 1", name="ck_anomaly_alerts_score"),
        sa.ForeignKeyConstraint(
            ["model_metadata_id"], ["model_metadata.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["verified_transaction_id"],
            ["verified_transactions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("verified_transaction_id"),
    )
    op.create_table(
        "category_corrections",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("verified_transaction_id", sa.String(length=36), nullable=False),
        sa.Column("previous_category_id", sa.String(length=100), nullable=True),
        sa.Column("new_category_id", sa.String(length=100), nullable=False),
        sa.Column("corrected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["new_category_id"], ["categories.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["previous_category_id"], ["categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["verified_transaction_id"],
            ["verified_transactions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("category_corrections", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_category_corrections_verified_transaction_id"),
            ["verified_transaction_id"],
            unique=False,
        )

    op.create_table(
        "user_flags",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("verified_transaction_id", sa.String(length=36), nullable=False),
        sa.Column("flag", sa.String(length=100), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["verified_transaction_id"],
            ["verified_transactions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "verified_transaction_id", "flag", name="uq_user_flags_transaction_flag"
        ),
    )
    with op.batch_alter_table("user_flags", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_flags_verified_transaction_id"),
            ["verified_transaction_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_flags", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_flags_verified_transaction_id"))

    op.drop_table("user_flags")
    with op.batch_alter_table("category_corrections", schema=None) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_category_corrections_verified_transaction_id")
        )

    op.drop_table("category_corrections")
    op.drop_table("anomaly_alerts")
    with op.batch_alter_table("verified_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verified_transactions_transaction_date"))
        batch_op.drop_index(batch_op.f("ix_verified_transactions_merchant"))
        batch_op.drop_index(batch_op.f("ix_verified_transactions_category_id"))
        batch_op.drop_index(batch_op.f("ix_verified_transactions_account_id"))
        batch_op.drop_index("ix_verified_transactions_account_date_amount")

    op.drop_table("verified_transactions")
    op.drop_table("statement_coverages")
    with op.batch_alter_table("raw_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_transactions_import_batch_id"))
        batch_op.drop_index(batch_op.f("ix_raw_transactions_canonical_fingerprint"))

    op.drop_table("raw_transactions")
    op.drop_table("import_contexts")
    with op.batch_alter_table("forecast_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_runs_account_id"))

    op.drop_table("forecast_runs")
    with op.batch_alter_table("balance_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_balance_snapshots_account_id"))

    op.drop_table("balance_snapshots")
    with op.batch_alter_table("scenarios", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenarios_account_id"))

    op.drop_table("scenarios")
    with op.batch_alter_table("savings_goals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_savings_goals_account_id"))

    op.drop_table("savings_goals")
    with op.batch_alter_table("recurring_series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recurring_series_account_id"))

    op.drop_table("recurring_series")
    with op.batch_alter_table("import_batches", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_import_batches_account_id"))

    op.drop_table("import_batches")
    with op.batch_alter_table("budgets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_budgets_user_profile_id"))

    op.drop_table("budgets")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_user_profile_id"))

    op.drop_table("accounts")
    op.drop_table("user_profiles")
    op.drop_table("model_metadata")
    op.drop_table("financial_roles")
    op.drop_table("categories")
    # ### end Alembic commands ###
