"""Statement-source adapters and import services."""

from cashflow_ai.imports.coverage import analyse_statement_coverage
from cashflow_ai.imports.csv_import_service import (
    ALLOWED_CSV_MIME_TYPES,
    persist_confirmed_csv,
)
from cashflow_ai.imports.csv_preview import (
    DEFAULT_MAX_CSV_BYTES,
    DEFAULT_PREVIEW_ROWS,
    CsvImportError,
    CsvImportErrorCode,
    parse_csv_document,
    preview_csv,
    validate_csv_import_plan,
)
from cashflow_ai.imports.duplicates import (
    PROBABLE_DUPLICATE_THRESHOLD,
    assess_duplicate_facts,
    assess_repeated_file,
    assess_statement_overlap,
    assess_transaction_duplicate,
    duplicate_facts_from_normalised,
    find_duplicate_assessments,
)
from cashflow_ai.imports.normalisation import (
    NORMALISER_IDENTITY,
    TransactionNormalisationError,
    calculate_file_hash,
    calculate_source_fingerprint,
    map_csv_row,
    normalise_csv_row,
    normalise_transaction,
    parse_amount_value,
    parse_date_value,
)
from cashflow_ai.imports.ocr_pdf import (
    DEFAULT_MAX_RENDER_PIXELS,
    DEFAULT_OCR_RENDER_DPI,
    OCR_EXTRACTOR_IDENTITY,
    OcrEngine,
    OcrWord,
    PytesseractOcrEngine,
    extract_ocr_pdf,
)
from cashflow_ai.imports.text_pdf import (
    DEFAULT_MAX_PDF_BYTES,
    DEFAULT_MAX_PDF_PAGES,
    DEFAULT_MIN_EMBEDDED_CHARACTERS,
    PDF_EXTRACTOR_IDENTITY,
    PdfImportError,
    PdfImportErrorCode,
    extract_text_pdf,
)

__all__ = [
    "ALLOWED_CSV_MIME_TYPES",
    "DEFAULT_MAX_CSV_BYTES",
    "DEFAULT_MAX_PDF_BYTES",
    "DEFAULT_MAX_PDF_PAGES",
    "DEFAULT_MAX_RENDER_PIXELS",
    "DEFAULT_MIN_EMBEDDED_CHARACTERS",
    "DEFAULT_OCR_RENDER_DPI",
    "DEFAULT_PREVIEW_ROWS",
    "NORMALISER_IDENTITY",
    "OCR_EXTRACTOR_IDENTITY",
    "PDF_EXTRACTOR_IDENTITY",
    "PROBABLE_DUPLICATE_THRESHOLD",
    "CsvImportError",
    "CsvImportErrorCode",
    "OcrEngine",
    "OcrWord",
    "PdfImportError",
    "PdfImportErrorCode",
    "PytesseractOcrEngine",
    "TransactionNormalisationError",
    "analyse_statement_coverage",
    "assess_duplicate_facts",
    "assess_repeated_file",
    "assess_statement_overlap",
    "assess_transaction_duplicate",
    "calculate_file_hash",
    "calculate_source_fingerprint",
    "duplicate_facts_from_normalised",
    "extract_ocr_pdf",
    "extract_text_pdf",
    "find_duplicate_assessments",
    "map_csv_row",
    "normalise_csv_row",
    "normalise_transaction",
    "parse_amount_value",
    "parse_csv_document",
    "parse_date_value",
    "persist_confirmed_csv",
    "preview_csv",
    "validate_csv_import_plan",
]
